---
- name: Install Docker, Jenkins, SonarQube, and Prometheus on localhost
  hosts: localhost
  become: yes
  tasks:

    # Step 1: Update the apt cache
    - name: Update apt cache
      apt:
        update_cache: yes

    # Step 2: Install Docker
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    # Step 3: Install Docker Compose
    - name: Install Docker Compose
      shell: |
        curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose
      when: ansible_distribution == 'Ubuntu'

    # Step 4: Start and enable Docker service
    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    # Step 5: Install Java
    - name: Install Java
      apt:
        name: openjdk-17-jdk
        state: present

    # Step 6: Install gpg if not already installed
    - name: Install gpg
      apt:
        name: gpg
        state: present

    # Step 7: Install Snapd
    - name: Install Snapd
      apt:
        name: snapd
        state: present

    # Step 8: Install Jenkins using Snap
    - name: Install Jenkins using Snap
      snap:
        name: jenkins
        classic: yes
        state: present

    # Step 9: Start and enable Jenkins service
    - name: Start and enable Jenkins service
      systemd:
        name: snap.jenkins.jenkins
        state: started
        enabled: yes

    # Step 10: Install Prometheus
    - name: Install Prometheus
      apt:
        name: prometheus
        state: present

    # Step 11: Install SonarQube
    - name: Create SonarQube directory
      file:
        path: /opt/sonarqube
        state: directory

    - name: Download SonarQube
      get_url:
        url: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-9.9.0.65466.zip
        dest: /opt/sonarqube/sonarqube.zip

    - name: Unzip SonarQube
      unarchive:
        src: /opt/sonarqube/sonarqube.zip
        dest: /opt/sonarqube
        remote_src: yes

    - name: Set ownership of SonarQube files
      file:
        path: /opt/sonarqube/sonarqube-9.9.0.65466
        owner: root
        group: root
        mode: "0755"
        recurse: yes

    # Step 12: Create a SonarQube systemd service file
    - name: Create SonarQube systemd service file
      copy:
        dest: /etc/systemd/system/sonarqube.service
        content: |
          [Unit]
          Description=SonarQube service
          After=network.target

          [Service]
          Type=simple
          User=root
          Group=root
          ExecStart=/opt/sonarqube/sonarqube-9.9.0.65466/bin/linux-x86-64/sonar.sh start
          ExecStop=/opt/sonarqube/sonarqube-9.9.0.65466/bin/linux-x86-64/sonar.sh stop
          Restart=on-failure
          LimitNOFILE=65536

          [Install]
          WantedBy=multi-user.target

    # Step 13: Reload systemd, start, and enable SonarQube service
    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Start and enable SonarQube service
      systemd:
        name: sonarqube
        state: started
        enabled: yes

    # Step 14: Start and enable Prometheus service
    - name: Start and enable Prometheus service
      systemd:
        name: prometheus
        state: started
        enabled: yes

